ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
ffplay -nodisp -autoexit /app/share/beeps/Oxygen-Im-Phone-Ring.ogg > /dev/null 2>&1
